sonar.projectKey=clementlegay_collector-shop
sonar.organization=clementlegay

sonar.sources=services/article-service/src,services/user-service/src,services/payment-service/src,services/fraud-detection-service/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=services/article-service/coverage/lcov.info,services/user-service/coverage/lcov.info,services/payment-service/coverage/lcov.info,services/fraud-detection-service/coverage/lcov.info
