apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: collector
data:
  init.sql: |
    CREATE DATABASE article_db;
    CREATE DATABASE user_db;
    CREATE DATABASE payment_db;
    CREATE DATABASE fraud_db;
    GRANT ALL PRIVILEGES ON DATABASE article_db TO collector;
    GRANT ALL PRIVILEGES ON DATABASE user_db TO collector;
    GRANT ALL PRIVILEGES ON DATABASE payment_db TO collector;
    GRANT ALL PRIVILEGES ON DATABASE fraud_db TO collector;

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: collector
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: collector
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: "collector"
            - name: POSTGRES_PASSWORD
              value: "collector_password"
            # Default DB, others created by init script
            - name: POSTGRES_DB
              value: "collector" 
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
