apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: collector
  labels:
    app.kubernetes.io/part-of: frontend
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: collector
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: frontend
        app: frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/instance: collector
    spec:
      containers:
        - name: frontend
          image: ghcr.io/clement-legay/collector-shop/frontend:sha-b0600268a12493010bafb1c3ed6b432b72f1cb9d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: "http://collector.local"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: frontend
  name: frontend
  namespace: collector
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: frontend
