apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: collector
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/clement-legay/collector-shop/frontend:sha-8560731571bd8c3ac98ab1e4c84d0db8142e37a0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: "http://collector.local"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: collector
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: frontend
